#!/bin/zsh
source $(echo $PWD)/env/env.setup
set_symlink () {
    src=$1
    dst=$2
    [ -e $src ] && [ ! -h $dst ] && ln -s $src $dst
}

i=0
print "Creating XDG directories..." >&2
xdg_dirs=(.cache .local/share .local/state .local/run .local/bin)
for dir in $xdg_dirs
do
    [[ -d $HOME/$dir ]] && continue
    mkdir -p $HOME/$dir
    print "$HOME/$dir" >&2
    ((i++))
done
[[ "$i" == 0 ]] && print "XDG directories already created." >&2
printf "\n"

j=0
print "Creating cache directories..." >&2
cache_dirs=(zsh brew brew/cache brew/logs vim node)
for dir in $cache_dirs
do
    [[ -d "$XDG_CACHE_HOME/$dir" ]] && continue
    mkdir -p "$XDG_CACHE_HOME/$dir"
    print "$XDG_CACHE_HOME/$dir" >&2
    ((j++))
done
[[ "$j" == 0 ]] && print "Cache directories already created." >&2
printf "\n"

[[ -d "$APPS/Visual Studio Code.app" ]] && VSCODE_BIN_PATH="$APPS/Visual Studio Code.app/Contents/Resources/app/bin/code"
set_symlink "$XDG_CONFIG_HOME/zsh/.zshenv" "$HOME/.zshenv"
[[ -n $VSCODE_BIN_PATH ]] && set_symlink "$VSCODE_BIN_PATH" "$XDG_BIN_HOME/code"

touch "$HOME/.hushlogin"
[[ -d "$HOME/.zsh_sessions" ]] && rm -rf "$HOME/.zsh_sessions"
[[ -a "$HOME/.zsh_history" ]] && rm "$HOME/.zsh_history"

echo "Success: paro-paro basic setup done."
